# Generated by Django 4.2 on 2024-03-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('dropdown_list', models.CharField(max_length=100)),
                ('payment', models.CharField(max_length=100)),
                ('terms_accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
