# Generated by Django 4.2 on 2024-03-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userdata_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
