# Generated by Django 4.2 on 2024-03-01 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_userdata_price_alter_userdata_profession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='terms_accepted',
            new_name='terms_and_conditions',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='price',
        ),
    ]
