# Generated by Django 4.2 on 2024-03-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_terms_accepted_userdata_terms_and_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
