# Generated by Django 4.2 on 2024-03-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userdata_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='payment',
        ),
    ]
