# Generated by Django 4.2 on 2024-03-05 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_dropdown_list_userdata_option_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='terms_and_conditions',
        ),
    ]
